export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_FEEDS_PENDING = 'REQUEST_FEEDS_PENDING';
export const REQUEST_FEEDS_SUCCESS = 'REQUEST_FEEDS_SUCCESS';
export const REQUEST_FEEDS_FAILED = 'REQUEST_FEEDS_FAILED';

export const REQUEST_SOURCES_PENDING = 'REQUEST_SOURCES_PENDING';
export const REQUEST_SOURCES_SUCCESS = 'REQUEST_SOURCES_SUCCESS';
export const REQUEST_SOURCES_FAILED = 'REQUEST_SOURCES_FAILED';

export const UPDATE_SOURCE_PENDING = 'UPDATE_SOURCE_PENDING';
export const UPDATE_SOURCE_SUCCESS = 'UPDATE_SOURCE_SUCCESS';
export const UPDATE_SOURCE_FAILED = 'UPDATE_SOURCE_FAILED';

export const CREATE_SOURCE_PENDING = 'CREATE_SOURCE_PENDING';
export const CREATE_SOURCE_SUCCESS = 'CREATE_SOURCE_SUCCESS';
export const CREATE_SOURCE_FAILED = 'CREATE_SOURCE_FAILED';

export const REQUEST_COUNTRIES_PENDING = 'REQUEST_COUNTRIES_PENDING';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILED = 'REQUEST_COUNTRIES_FAILED';

export const REQUEST_SOURCE_TYPES_PENDING = 'REQUEST_SOURCE_TYPES_PENDING';
export const REQUEST_SOURCE_TYPES_SUCCESS = 'REQUEST_SOURCE_TYPES_SUCCESS';
export const REQUEST_SOURCE_TYPES_FAILED = 'REQUEST_SOURCE_TYPES_FAILED';

export const REQUEST_SOURCE_STATUSES_PENDING = 'REQUEST_SOURCE_STATUSES_PENDING';
export const REQUEST_SOURCE_STATUSES_SUCCESS = 'REQUEST_SOURCE_STATUSES_SUCCESS';
export const REQUEST_SOURCE_STATUSES_FAILED = 'REQUEST_SOURCE_STATUSES_FAILED';
