export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_FEEDS_PENDING = 'REQUEST_FEEDS_PENDING';
export const REQUEST_FEEDS_SUCCESS = 'REQUEST_FEEDS_SUCCESS';
export const REQUEST_FEEDS_FAILED = 'REQUEST_FEEDS_FAILED';

export const REQUEST_SOURCES_PENDING = 'REQUEST_SOURCES_PENDING';
export const REQUEST_SOURCES_SUCCESS = 'REQUEST_SOURCES_SUCCESS';
export const REQUEST_SOURCES_FAILED = 'REQUEST_SOURCES_FAILED';

export const UPDATE_SOURCE_PENDING = 'UPDATE_SOURCE_PENDING';
export const UPDATE_SOURCE_SUCCESS = 'UPDATE_SOURCE_SUCCESS';
export const UPDATE_SOURCE_FAILED = 'UPDATE_SOURCE_FAILED';

export const CREATE_SOURCE_PENDING = 'CREATE_SOURCE_PENDING';
export const CREATE_SOURCE_SUCCESS = 'CREATE_SOURCE_SUCCESS';
export const CREATE_SOURCE_FAILED = 'CREATE_SOURCE_FAILED';

export const REQUEST_COUNTRIES_PENDING = 'REQUEST_COUNTRIES_PENDING';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILED = 'REQUEST_COUNTRIES_FAILED';

export const REQUEST_SOURCE_TYPES_PENDING = 'REQUEST_SOURCE_TYPES_PENDING';
export const REQUEST_SOURCE_TYPES_SUCCESS = 'REQUEST_SOURCE_TYPES_SUCCESS';
export const REQUEST_SOURCE_TYPES_FAILED = 'REQUEST_SOURCE_TYPES_FAILED';

export const REQUEST_SOURCE_STATUSES_PENDING = 'REQUEST_SOURCE_STATUSES_PENDING';
export const REQUEST_SOURCE_STATUSES_SUCCESS = 'REQUEST_SOURCE_STATUSES_SUCCESS';
export const REQUEST_SOURCE_STATUSES_FAILED = 'REQUEST_SOURCE_STATUSES_FAILED';

export const REQUEST_SOURCE_STATS_PENDING = 'REQUEST_SOURCE_STATS_PENDING';
export const REQUEST_SOURCE_STATS_SUCCESS = 'REQUEST_SOURCE_STATS_SUCCESS';
export const REQUEST_SOURCE_STATS_FAILED = 'REQUEST_SOURCE_STATS_FAILED';

export const REQUEST_GENERAL_COUNTERS_PENDING = 'REQUEST_GENERAL_COUNTERS_PENDING';
export const REQUEST_GENERAL_COUNTERS_SUCCESS = 'REQUEST_GENERAL_COUNTERS_SUCCESS';
export const REQUEST_GENERAL_COUNTERS_FAILED = 'REQUEST_GENERAL_COUNTERS_FAILED';



export const REQUEST_FEEDS_BY_SOURCE_PENDING = 'REQUEST_FEEDS_BY_SOURCE_PENDING';
export const REQUEST_FEEDS_BY_SOURCE_SUCCESS = 'REQUEST_FEEDS_BY_SOURCE_SUCCESS';
export const REQUEST_FEEDS_BY_SOURCE_FAILED = 'REQUEST_FEEDS_BY_SOURCE_FAILED';
export const REQUEST_FEEDS_BY_DAY_PENDING = 'REQUEST_FEEDS_BY_DAY_PENDING';
export const REQUEST_FEEDS_BY_DAY_SUCCESS = 'REQUEST_FEEDS_BY_DAY_SUCCESS';
export const REQUEST_FEEDS_BY_DAY_FAILED = 'REQUEST_FEEDS_BY_DAY_FAILED';
export const REQUEST_FEEDS_BY_SOURCE_DAY_PENDING = 'REQUEST_FEEDS_BY_SOURCE_DAY_PENDING';
export const REQUEST_FEEDS_BY_SOURCE_DAY_SUCCESS = 'REQUEST_FEEDS_BY_SOURCE_DAY_SUCCESS';
export const REQUEST_FEEDS_BY_SOURCE_DAY_FAILED = 'REQUEST_FEEDS_BY_SOURCE_DAY_FAILED';

export const START_FEED_RUNNER = "START_FEED_RUNNER";
export const START_FEED_RUNNER_SUCCESS = "START_FEED_RUNNER_SUCCESS";
export const START_FEED_RUNNER_FAILED = "START_FEED_RUNNER_FAILED";
export const STOP_FEED_RUNNER = "STOP_FEED_RUNNER";
export const STOP_FEED_RUNNER_SUCCESS = "STOP_FEED_RUNNER_SUCCESS";
export const STOP_FEED_RUNNER_FAILED = "STOP_FEED_RUNNER_FAILED";

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

